### ISSUE TITLE
Regards on Modeling Rewards Signaling

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/synthrl#5]
Reward Signals is one of the common reasons why RL(and at the same time, Game Theory) works well; it guides RL agents to move toward the ideal goal. Needless to say in Multi-Agent RL(MARL) problems as well.

### Synthesizer vs Verifier
Note that our `SynthRL` is based on CEGIS(especially OGIS). We formulate the OGIS in RL problem. Thus, the problem involves the interaction between two agents: Syntherisizer and Verifier.

Synthesizer may want to synthesizer well, satisfying test case constraints. However, NOT JUST WELL. It must synthesize **non-ambiguous program** well. How could we guide the synthesizer to do so? One obvious way is by leveraging the Verifier's reward signal(to us, it is state value of Verifier). In a way that Verifier may have a less potential reward(i.e, Verifier won't produce semantically equivalent program well), the more possibility that Synthesizer will produce a non-ambiguous program, and therefore become close to the desired ideal, generalized, program.

### Ablation Study

Reward signaling will be the most unique feature of our `SynthRL`, distinguishing from other program synthesis researches. However, empirical ablation study should be operated answer:

_RQ. RL based synthesis with Reward signaling from verifier vs without signaling_

**Comment by henrylee97** [comment]
### Merely replacing SMT solver (in synthesizing) is not enough unique research.

We will be replacing the SMT solver for a synthesizer. Instead of solving some logical formula to find the desired program, we compose a (learned) agent, and the agent will synthesizer the program according to learned policy.

This is not enough. We may want to synthesize **better**. To do so may be leveraging signals from the verifier.
